name: Storybook Deployment

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm i; cd storybook; npm i @mybldr/ui;

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            cd storybook;
            npm run build-storybook;
            az storage blob upload-batch --account-name 'bldreastustststorybook' --auth-mode key -d '$web' -s ./storybook-static

      # Azure logout
      - name: logout
        run: |
          az logout
        if: always()
