name: Storybook Deployment

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm i; cd storybook; npm i @mybldr/ui;

      - name: Build Storybook
        run: cd storybook; npm run build-storybook;

      - uses: azure/login@v2
        with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name 'bldreastustststorybook' --auth-mode key -d '$web' -s ../../storybook/storybook-static

      # Azure logout
      - name: logout
        run: |
          az logout
        if: always()
