name: Storybook Deployment

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        # Remove package-lock to avoid issues with rollup deps that aren't cross platform (@rollup/rollup-linux-x64-gnu)
        run: rm package-lock.json; npm i;

      - name: Build Storybook
        run: npm run build-storybook;

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload to blob storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name bldreastustststorybook --account-key ${{ secrets.AZURE_STORAGE_KEY }} -d '$web' -s storybook-static --overwrite

      # Azure logout
      - name: logout
        run: |
          az logout
        if: always()
